"""Complex Hermite (Ito) moment features for grayscale images.

Convention
----------
Everything below is pinned to the ``c = 1`` normalisation, meaning the
reference Gaussian is

    dgamma(z) = (1/pi) * exp(-|z|^2) dA(z),    E_gamma |Z|^2 = 1

and the complex Hermite polynomials are generated by

    exp(lam*z + mu*z_bar - lam*mu) = sum_{a,b} H_{a,b} lam^a mu^b / (a! b!)

    H_{a,b}(z, z_bar) = sum_k (-1)^k k! C(a,k) C(b,k) z^(a-k) z_bar^(b-k)

Three things have to agree for the basis to be orthonormal, and they do here:

  1. the radial window is exp(-r^2 / 2)  -- i.e. sqrt of the c=1 Gaussian,
  2. the polynomial sign factor is (-1)^k -- i.e. c=1,
  3. the data is rescaled so that E_mu |Z|^2 = 1 (``moment_scale``).

With those, psi_{a,b} = H_{a,b} * exp(-|z|^2/2) / sqrt(pi * a! * b!) satisfies

    integral psi_{a,b} * conj(psi_{a',b'}) dA = delta_{aa'} delta_{bb'}

so Euclidean distance between coefficient vectors is L2 distance between the
(windowed) densities, and Parseval holds.

Equivariance
------------
Rotating the image by theta multiplies each coefficient by a pure phase:

    c_{a,b}[R_theta f] = exp(i * (a - b) * theta) * c_{a,b}[f]

The phase order is k = a - b, exposed by ``phase_orders``. Note the sign: the
coefficient labelled ``(a, b)`` is the expectation of H_{a,b} itself (the
moment convention), *not* of its conjugate. Downstream invariant builders must
use k = a - b, not b - a, or the resulting features come out mirrored.
"""

import math

import torch


def gaussian_window(r):
    """The c=1 window, exp(-r^2 / 2).

    This is the only window for which the basis below is orthonormal. Others
    (see ``window_sweep.WINDOWS``) still give usable, still-equivariant
    features -- any radial profile preserves the phase law -- but Parseval and
    the moment identities are lost, and per-mode scale has to be fixed
    downstream by a StandardScaler.
    """
    return torch.exp(-(r ** 2) / 2.0)




class MomentTransform:
    """Image -> complex Hermite coefficients (Gaussian-weighted).

    Each image is treated as a density map: normalised to unit mass, recentred
    on its centroid, rescaled to second moment ``moment_scale``, then projected
    onto the complex Hermite basis.

    Parameters
    ----------
    max_degree : int
        Keep all modes with a + b <= max_degree.
    moment_scale : float
        Target for E_mu |Z|^2 after rescaling. 1.0 matches the window exactly
        and is the principled default. Values a little below 1 (0.5-1.0) push
        mass inward, where the window is flatter, and often give faster
        coefficient decay at fixed degree; it is rotation-invariant either way,
        so equivariance is untouched. Worth sweeping once as a hyperparameter.
    window : callable
        ``w(r) -> weights`` over the radius r = |z|.
    """

    def __init__(self, max_degree=6, moment_scale=3.0, window=gaussian_window):
        self.max_degree = max_degree
        self.moment_scale = moment_scale
        self.window = window

    # -- normalisation -----------------------------------------------------

    def prepare_density_center(self, images):
        """Normalise to a probability density and recentre on the centroid."""
        density = images / (images.sum(dim=(-2, -1), keepdim=True) + 1e-9)

        rows, cols = images.shape[-2], images.shape[-1]
        y_grid, x_grid = torch.meshgrid(
            torch.arange(rows, device=images.device, dtype=density.dtype),
            torch.arange(cols, device=images.device, dtype=density.dtype),
            indexing='ij',
        )

        # Rows index downward, so (x, y) is a left-handed frame: the phase law
        # holds exactly, but the sense of positive theta is flipped relative to
        # the usual maths convention. Consistent, just worth knowing.
        x = x_grid - (density * x_grid).sum(dim=(-2, -1), keepdim=True)
        y = y_grid - (density * y_grid).sum(dim=(-2, -1), keepdim=True)
        return density, x, y

    def second_moment_trace(self, density, x, y):
        """Trace of the covariance matrix (the mean squared radius)."""
        p_xx = (density * x * x).sum(dim=(-2, -1))
        p_yy = (density * y * y).sum(dim=(-2, -1))
        return p_xx + p_yy

    def normalize_scale(self, x, y, trace):
        """Rescale so that E_mu |Z|^2 == moment_scale (scale invariance)."""
        scale = torch.sqrt(trace / self.moment_scale + 1e-12)[..., None, None]
        return x / scale, y / scale

    # -- basis -------------------------------------------------------------

    def _hermite_rows(self, z, z_bar):
        """Yield ``(a, row)`` where ``row[b]`` is H_{a,b}, for a + b <= d.

        Uses the two-term recurrences implied by the generating function

            H_{a+1,b} = z * H_{a,b} - b * H_{a,b-1}
            H_{a,b+1} = z_bar * H_{a,b} - a * H_{a-1,b}

        seeded with H_{0,0} = 1. This is O(d^2) total instead of re-expanding
        the explicit alternating sum for every mode, and avoids the
        cancellation in that sum, which starts to hurt around d >= 12. Only one
        row is held at a time, so peak memory is O(d) tensors, not O(d^2).
        """
        d = self.max_degree

        # a = 0: H_{0,b} = z_bar^b  (the a * H_{a-1,b} term vanishes)
        row = [torch.ones_like(z)]
        for _ in range(1, d + 1):
            row.append(z_bar * row[-1])
        yield 0, row

        for a in range(1, d + 1):
            prev, row = row, []
            for b in range(0, d - a + 1):
                H = z * prev[b]
                if b > 0:
                    H = H - b * prev[b - 1]
                row.append(H)
            yield a, row

    # -- projection --------------------------------------------------------

    def complex_coefficients(self, images):
        """Project each image onto the complex Hermite basis, mode by mode.

        Returns ``(coeffs, index)`` where ``coeffs`` has shape ``(B, K)`` and
        ``index`` lists the ``(a, b)`` degree pair for each column. Only the
        half-triangle a >= b is emitted; for real images the rest follows from
        c_{b,a} = conj(c_{a,b}).
        """
        density, xc, yc = self.prepare_density_center(images)
        trace = self.second_moment_trace(density, xc, yc)
        xn, yn = self.normalize_scale(xc, yc, trace)

        z = torch.complex(xn, yn)
        z_bar = torch.conj(z)
        r_sq = xn ** 2 + yn ** 2
        window = self.window(torch.sqrt(r_sq + 1e-12))
        weight = (density * window).to(z.dtype)

        coeffs, index = [], []
        for a, row in self._hermite_rows(z, z_bar):
            for b in range(min(a, self.max_degree - a) + 1):
                norm = 1.0 / math.sqrt(
                    math.pi * math.factorial(a) * math.factorial(b)
                )
                # Expectation of psi_{a,b} under the density: keeps memory at
                # O(B) per mode instead of materialising the full basis tensor.
                coeffs.append(norm * (weight * row[b]).sum(dim=(-2, -1)))
                index.append((a, b))

        return torch.stack(coeffs, dim=-1), index

    def index(self):
        """The ``(a, b)`` pairs, in the same order as the coefficient columns."""
        return [
            (a, b)
            for a in range(self.max_degree + 1)
            for b in range(min(a, self.max_degree - a) + 1)
        ]

    def phase_orders(self):
        """k = a - b for each column: the rotation phase order exp(i*k*theta)."""
        return [a - b for a, b in self.index()]


def check_equivariance(transform, images, atol=1e-4):
    """Verify the phase law against an exact 90-degree raster rotation.

    ``rot90`` involves no interpolation, so any error here is a bug in the
    geometry rather than resampling noise. The frame handedness fixes the sign
    of theta, so both +pi/2 and -pi/2 are tried and the better one reported.
    """
    c0, index = transform.complex_coefficients(images)
    c1, _ = transform.complex_coefficients(torch.rot90(images, 1, (-2, -1)))

    errors = []
    for sign in (+1, -1):
        phase = torch.tensor(
            [(1j * sign) ** (a - b) for a, b in index],
            dtype=c0.dtype,
            device=c0.device,
        )
        errors.append((c1 - phase * c0).abs().max().item())

    error = min(errors)
    return error < atol, error